//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLSaveFileEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YLSaveFileEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;player&quot;: {
        ///        &quot;playtime&quot;: 0,
        ///        &quot;arcadeTokenCount&quot;: 0,
        ///        &quot;healthExtenderTokenCount&quot;: 0,
        ///        &quot;specialExtenderTokenCount&quot;: 0,
        ///        &quot;moveEnabled&quot;: [
        ///            0,
        ///            0,
        ///            0,
        ///            0,
        ///            0,
        ///            0,
        ///            0,
        ///            0,
        ///            0,
        ///            0,
        ///            0,
        ///            0,
        ///            0,
        ///            0,
        ///            0,
        ///            0,
        ///            0
        ///        ],
        ///        &quot;paidTrowza&quot;: 0,
        ///        &quot;unspentPagies&quot;: 0,
        ///        &quot;spentCasi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _0_ {
            get {
                return ResourceManager.GetString("_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;player&quot;: {
        ///        &quot;playtime&quot;: 95774,
        ///        &quot;arcadeTokenCount&quot;: 5,
        ///        &quot;healthExtenderTokenCount&quot;: 6,
        ///        &quot;specialExtenderTokenCount&quot;: 6,
        ///        &quot;moveEnabled&quot;: [
        ///            1,
        ///            1,
        ///            1,
        ///            1,
        ///            1,
        ///            1,
        ///            1,
        ///            0,
        ///            1,
        ///            1,
        ///            1,
        ///            1,
        ///            1,
        ///            1,
        ///            1,
        ///            1,
        ///            1
        ///        ],
        ///        &quot;paidTrowza&quot;: 470,
        ///        &quot;unspentPagies&quot;: 74,
        ///        &quot;sp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _100_ {
            get {
                return ResourceManager.GetString("_100_", resourceCulture);
            }
        }
    }
}
